//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BookingEntities : DbContext
    {
        public DB_BookingEntities()
            : base("name=DB_BookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<TO> TO { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
