//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO
    {
        public TO() { }

        public TO(string ExternalFIO, string ExternalLogin, string ExternalPassword)
        {
            FIO = ExternalFIO;
            Login = ExternalLogin;
            Password = ExternalPassword;
        }

        public int Id { get; set; }
        public string FIO { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}
